# Generated by Django 3.1.6 on 2021-02-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AddressGeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_code', models.CharField(max_length=5)),
                ('continent_name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=20)),
                ('region_code', models.CharField(max_length=5)),
                ('region_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geoname_id', models.IntegerField()),
                ('capital', models.CharField(max_length=20)),
                ('country_flag', models.CharField(max_length=50)),
                ('country_flag_emoji', models.CharField(max_length=50)),
                ('country_flag_emoji_unicode', models.CharField(max_length=50)),
                ('calling_code', models.CharField(max_length=5)),
                ('is_eu', models.BooleanField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_data', to='address.address')),
                ('languages', models.ManyToManyField(related_name='address_geo_data', to='language.Language')),
            ],
        ),
    ]
